Repository TerminalFi/LSP-copilot, pull requests merged in 2022-08, with the labels that each got.

#41 fix: scroll view to make full completed text visible
  plugin/commands.py
  plugin/ui/panel_completion.py
Labels: enhancement

#42 refactor: remove default when getting existing settings
  plugin/commands.py
  plugin/listeners.py
  plugin/ui/completion.py
  plugin/utils.py
Labels: refactor

#40 refactor: better completion debounce implementation
  plugin/commands.py
  plugin/constants.py
  plugin/listeners.py
  plugin/plugin.py
  plugin/utils.py
Labels: refactor

#44 docs: LSP-copilot is on Package Control
  README.md
Labels: documentation

#46 tentative refactoring for #27
  plugin/listeners.py
  plugin/ui/completion.py
Labels: refactor

#47 refactor: remove polyfill for LspWindowCommand
  plugin/commands.py
Labels: refactor

#27 feat: add phantom completion
  LSP-copilot.sublime-settings
  plugin/commands.py
  plugin/listeners.py
  plugin/plugin.py
  plugin/ui/completion.py
  sublime-package.json
Labels: enhancement
