Repository TerminalFi/LSP-copilot, pull requests merged in 2022-07, with the labels that each got.

#18 feat: panel completions
  Main.sublime-commands
  commands.py
  constants.py
  listeners.py
  plugin.py
  types.py
  ui/__init__.py
  ui/completion.py
  ui/panel_completion.py
  utils.py
Labels: enhancement

#26 feat: hook to auto_complete command
  LSP-copilot.sublime-settings
  commands.py
  listeners.py
  sublime-package.json
Labels: enhancement

#24 refactor: move plugin files to `plugin/`
  boot.py
  plugin/__init__.py
  plugin/commands.py
  plugin/constants.py
  plugin/listeners.py
  plugin/plugin.py
  plugin/types.py
  plugin/ui/__init__.py
  plugin/ui/completion.py
  plugin/ui/panel_completion.py
  plugin/utils.py
  pyproject.toml
Labels: refactor

#32 fix: PHP syntax highlighting in completions
  plugin/ui/completion.py
  plugin/ui/panel_completion.py
  plugin/utils.py
Labels: bug

#35 feat: local checks setting
  LSP-copilot.sublime-settings
  plugin/commands.py
  plugin/types.py
  sublime-package.json
Labels: enhancement

#31 fix: wrong `is_visible` status for completion
  plugin/ui/completion.py
Labels: bug

#34 fix: wrong syntax highlighting for embedded languages
  plugin/ui/completion.py
  plugin/ui/panel_completion.py
  plugin/utils.py
Labels: bug

#37 refactor: get plugin version from package metadata file
  plugin/constants.py
  plugin/plugin.py
Labels: refactor

#38 fix: LocalChecksOnly: update to correct parameter, update additional return status
  plugin/commands.py
  plugin/types.py
Labels: bug

#29 feat: implement getCompletionCycling
  plugin/commands.py
  plugin/plugin.py
  plugin/utils.py
Labels: enhancement
